package com.app.pojos;

public enum Category {
	FANTASY, FICTION, SCI_FI,MOTIVATIONAL,ADVENTURE,ROMANCE,SPORTS,NATURE,SELF_HELP,HISTORY,BIOGRAPHY,TRUE_CRIME,PHILOSOPHY,MYSTERY,CHILDREN_LITERATURE,SCIENCE,EDUCATIONAL,MISC
}
